// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroTools.Data;

#nullable disable

namespace RetroTools.Data.Migrations
{
    [DbContext(typeof(RetroToolsDbContext))]
    [Migration("20260729155447_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RetroTools.Data.Entities.Palette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("palettes", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PaletteEntry", b =>
                {
                    b.Property<long>("PaletteId")
                        .HasColumnType("bigint");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<int>("HardwareColorIndex")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("PaletteId", "SlotIndex");

                    b.ToTable("palette_entries", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PlatformModeRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("BitsPerPixel")
                        .HasColumnType("int");

                    b.Property<int>("CellHeight")
                        .HasColumnType("int");

                    b.Property<int>("CellWidth")
                        .HasColumnType("int");

                    b.Property<int>("ColorScope")
                        .HasColumnType("int");

                    b.Property<int?>("FixedHeight")
                        .HasColumnType("int");

                    b.Property<int?>("FixedWidth")
                        .HasColumnType("int");

                    b.Property<int>("HeightAlignment")
                        .HasColumnType("int");

                    b.Property<bool>("IsHardwareSprite")
                        .HasColumnType("bit(1)");

                    b.Property<int>("MaxColorsPerCell")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<int>("PaletteSlots")
                        .HasColumnType("int");

                    b.Property<int>("PixelAspectHeight")
                        .HasColumnType("int");

                    b.Property<int>("PixelAspectWidth")
                        .HasColumnType("int");

                    b.Property<string>("PlatformCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("int");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsMask")
                        .HasColumnType("bit(1)");

                    b.Property<int>("WidthAlignment")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("PlatformCode");

                    b.ToTable("platform_modes", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PlatformRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("ColorCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasHardwareSprites")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("HasProgrammablePalette")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("ModeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaletteProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PlatformCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeCode");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlatformCode");

                    b.HasIndex("OwnerId", "Name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Sprite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasMask")
                        .HasColumnType("bit(1)");

                    b.Property<int>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("MetaJson")
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("PaletteId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PaletteId");

                    b.HasIndex("ProjectId");

                    b.ToTable("sprites", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("AttributeData")
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("MaskData")
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<byte[]>("PixelData")
                        .IsRequired()
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<long>("SpriteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpriteId", "FrameIndex")
                        .IsUnique();

                    b.ToTable("sprite_frames", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("sprite_groups", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CellHeightPx")
                        .HasColumnType("int");

                    b.Property<int>("CellWidthPx")
                        .HasColumnType("int");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("spritemaps", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteMapCell", b =>
                {
                    b.Property<long>("SpriteMapId")
                        .HasColumnType("bigint");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<int>("FrameIndex")
                        .HasColumnType("int");

                    b.Property<long?>("SpriteId")
                        .HasColumnType("bigint");

                    b.HasKey("SpriteMapId", "Column", "Row");

                    b.HasIndex("SpriteId");

                    b.ToTable("spritemap_cells", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit(1)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.UserLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("datetime(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Provider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Palette", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Project", "Project")
                        .WithMany("Palettes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PaletteEntry", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Palette", "Palette")
                        .WithMany("Entries")
                        .HasForeignKey("PaletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Palette");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PlatformModeRecord", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.PlatformRecord", "Platform")
                        .WithMany("Modes")
                        .HasForeignKey("PlatformCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Project", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.PlatformModeRecord", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetroTools.Data.Entities.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroTools.Data.Entities.PlatformRecord", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mode");

                    b.Navigation("Owner");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Sprite", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.SpriteGroup", "Group")
                        .WithMany("Sprites")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetroTools.Data.Entities.Palette", "Palette")
                        .WithMany()
                        .HasForeignKey("PaletteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetroTools.Data.Entities.Project", "Project")
                        .WithMany("Sprites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Palette");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteFrame", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Sprite", "Sprite")
                        .WithMany("Frames")
                        .HasForeignKey("SpriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprite");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteGroup", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteMap", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Project", "Project")
                        .WithMany("SpriteMaps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteMapCell", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.Sprite", "Sprite")
                        .WithMany()
                        .HasForeignKey("SpriteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetroTools.Data.Entities.SpriteMap", "SpriteMap")
                        .WithMany("Cells")
                        .HasForeignKey("SpriteMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprite");

                    b.Navigation("SpriteMap");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.UserLogin", b =>
                {
                    b.HasOne("RetroTools.Data.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Palette", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.PlatformRecord", b =>
                {
                    b.Navigation("Modes");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Project", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Palettes");

                    b.Navigation("SpriteMaps");

                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.Sprite", b =>
                {
                    b.Navigation("Frames");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteGroup", b =>
                {
                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.SpriteMap", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("RetroTools.Data.Entities.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
